export function trimUSDT(symbol: String): string {
  return symbol.replace("USDT", "");
}

export function roundNum(num: number): number {
  if (num > 100) {
    return Math.round(num * 100) / 100;
  } else if (num > 1) {
    return Math.round(num * 1000) / 1000;
  } else if (num > 0.01) {
    return Math.round(num * 100000) / 100000;
  } else if (num > 0.0001) {
    return Math.round(num * 10000000) / 10000000;
  } else {
    return Math.round(num * 100000000) / 100000000;
  }
}

export const TradingSymbols = [
  "BTCUSDT",
  "ETHUSDT",
  "ETCUSDT",
  "OPUSDT",
  "SOLUSDT",
  "APEUSDT",
  "BNBUSDT",
  "FILUSDT",
  "MATICUSDT",
  "GMTUSDT",
  "NEARUSDT",
  "DOTUSDT",
  "AVAXUSDT",
  "ADAUSDT",
  "ENSUSDT",
  "XRPUSDT",
  "LITUSDT",
  "UNIUSDT",
  "UNFIUSDT",
  "CRVUSDT",
  "FTMUSDT",
  "SANDUSDT",
  "LINKUSDT",
  "GALAUSDT",
  "1000SHIBUSDT",
  "PEOPLEUSDT",
  "AXSUSDT",
  "CHZUSDT",
  "GALAUSDT",
  "BCHUSDT",
  "SNXUSDT",
  "RUNEUSDT",
  "DYDXUSDT",
  "WAVESUSDT",
  "AAVEUSDT",
  "LTCUSDT",
  "DOGEUSDT",
  "VETUSDT",
  "TRBUSDT",
  "ATOMUSDT",
  "TOMOUSDT",
  "CTKUSDT",
  "THETAUSDT",
  "MANAUSDT",
  "ENJUSDT",
  "EOSUSDT",
  "FLMUSDT",
  "YFIUSDT",
  "SUSHIUSDT",
  "ROSEUSDT",
  "RLCUSDT",
  "JASMYUSDT",
  "KAVAUSDT",
  "HOTUSDT",
  "ICPUSDT",
  "XMRUSDT",
  "TRXUSDT",
  "IOTXUSDT",
  "1INCHUSDT",
  "IMXUSDT",
  "LINAUSDT",
  "ALGOUSDT",
  "ZILUSDT",
  "ZECUSDT",
  "RSRUSDT",
  "XTZUSDT",
  "ONEUSDT",
  "DENTUSDT",
  "OCEANUSDT",
  "TLMUSDT",
  "ALICEUSDT",
  "EGLDUSDT",
  "GRTUSDT",
  "SCUSDT",
  "ARUSDT",
  "KNCUSDT",
  "ALPHAUSDT",
  "QTUMUSDT",
  "RVNUSDT",
  "COMPUSDT",
  "BELUSDT",
  "ANKRUSDT",
  "BTSUSDT",
  "ARPAUSDT",
  "LPTUSDT",
  "LRCUSDT",
  "MTLUSDT",
  "CHRUSDT",
  "XLMUSDT",
  "SRMUSDT",
  "OGNUSDT",
  "BANDUSDT",
  "STORJUSDT",
  "GTCUSDT",
  "WOOUSDT",
  "FLOWUSDT",
  "COTIUSDT",
  "CELRUSDT",
  "BAKEUSDT",
  "MASKUSDT",
  "AUDIOUSDT",
  "KSMUSDT",
  "RAYUSDT",
  "HBARUSDT",
  "NEOUSDT",
  "OMGUSDT",
  "API3USDT",
  "HNTUSDT",
  "C98USDT",
  "STMXUSDT",
  "SXPUSDT",
  "DASHUSDT",
  "ATAUSDT",
  "DARUSDT",
  "BATUSDT",
  "BALUSDT",
  "ONTUSDT",
  "ZRXUSDT",
  "DUSKUSDT",
  "SFPUSDT",
  "FTTUSDT",
  "KLAYUSDT",
  "XEMUSDT",
  "SKLUSDT",
  "IOTAUSDT",
  "ICXUSDT",
  "CELOUSDT",
  "CVCUSDT",
  "IOSTUSDT",
  "MKRUSDT",
  "BLZUSDT",
  "REEFUSDT",
  "NKNUSDT",
  "RENUSDT",
  "BNXUSDT",
  "DGBUSDT",
  "ANTUSDT",
  "ZENUSDT",
  "CTSIUSDT",
  "DEFIUSDT",
  "BCDOMUSDT",
  "1000XECUSDT",
];
