export enum AnalyzeStrategy {
  RSI = "RSI",
  RSI_WITH_MA = "RSI_WITH_MA",
  RSI_DIVERGENCE = "RSI_DIVERGENCE",
  RSI_TRIPLE_DIVERGENCE = "RSI_TRIPLE_DIVERGENCE",
  BOLLINGER_BAND = "BOLLINGER_BAND",
  RSI_WITH_BB = "RSI_WITH_BB",
  CONTINUOUS_TREND = "CONTINUOUS_TREND",
  EXTENDED_CANDLE = "EXTENDED_CANDLE",
  NOT_AVAILABLE = "NOT_AVAILABLE",
}
