export enum AnalyzeStrategy {
  RSI_BULLISH = "RSI_BULLISH",
  RSI_WITH_MA_BULLISH = "RSI_WITH_MA_BULLISH",
  RSI_BULLISH_DIVERGENCE = "RSI_BULLISH_DIVERGENCE",
  BOLLINGER_BAND_BULLISH = "BOLLINGER_BAND_BULLISH",
  NOT_AVAILABLE = "NOT_AVAILABLE",
}
